#%RAML 1.0
title: "Microservicio"
version: 1.0

/api/sps/helloworld/v1:
  description: Endpoint que recibe y devuelve las entradas
  /ordenar:
    post:
      description: |
        Endpoint para ordenar una comida
      body:
        application/json:
          example: |
            {"id_cliente": 1,"id_comida": 2,"time": "2018-09-22T12:42:31Z"}
      responses:
        200:
          body:
            application/json:
              example: |
                {"message": "Orden realizada con exito!"}
        400:
          body:
            application/json:
              example: |
                {"message": "Error en la estructura del body"}
        404:
          body:
            application/json:
              example: |
                {"message": "No se ha encontrado el usuario"}
